# Generated by Django 4.2.19 on 2026-03-02 15:32

from django.db import migrations, models
import django.db.models.deletion
import tenant_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_data', '0002_alert_alertstate_tag_comment_auditlog_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('imap', 'IMAP'), ('rest', 'REST'), ('webhook', 'Webhook')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('severity_map', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300)),
                ('secrets_ref', models.CharField(blank=True, max_length=255)),
                ('webhook_api_key', models.CharField(default=tenant_data.models.generate_api_key, max_length=64)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('never', 'Never'), ('healthy', 'Healthy'), ('error', 'Error')], default='never', max_length=20)),
                ('health_details', models.JSONField(blank=True, default=dict)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenant_data.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('webhook', 'Webhook'), ('test', 'Test')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('error', 'Error')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='tenant_data.source')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='IngestionEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('error', 'Error'), ('ignored', 'Ignored')], max_length=20)),
                ('parse_error', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('raw_preview', models.JSONField(blank=True, default=dict)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_data.alert')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenant_data.ingestionrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='tenant_data.source')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DedupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint_fields', models.JSONField(blank=True, default=list)),
                ('strategy', models.CharField(choices=[('increment_occurrence', 'Increment Occurrence')], default='increment_occurrence', max_length=40)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dedup_policy', to='tenant_data.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
