# Generated by Django 4.2.19 on 2026-03-02 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_data', '0003_source_sourceconfig_ingestionrun_ingestioneventlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='parse_error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='parsed_field_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='alert',
            name='parsed_payload',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ParserRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('config_text', models.TextField()),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parser_revisions', to=settings.AUTH_USER_MODEL)),
                ('parser_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tenant_data.parserdefinition')),
                ('rollback_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_children', to='tenant_data.parserrevision')),
            ],
            options={
                'ordering': ('-version', '-id'),
                'unique_together': {('parser_definition', 'version')},
            },
        ),
        migrations.AddField(
            model_name='parserdefinition',
            name='active_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenant_data.parserrevision'),
        ),
        migrations.AddField(
            model_name='parserdefinition',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parser_definition', to='tenant_data.source'),
        ),
    ]
