# Generated by Django 4.2.19 on 2026-03-03 18:26

from django.conf import settings
from django.db import connection, migrations, models
import django.db.models.deletion


def backfill_customer_relations(apps, schema_editor):
    Customer = apps.get_model("tenant_data", "Customer")
    Alert = apps.get_model("tenant_data", "Alert")
    Source = apps.get_model("tenant_data", "Source")
    SavedSearch = apps.get_model("tenant_data", "SavedSearch")
    NotificationEvent = apps.get_model("tenant_data", "NotificationEvent")
    IngestionRun = apps.get_model("tenant_data", "IngestionRun")

    schema_name = (getattr(connection, "schema_name", None) or "legacy").strip() or "legacy"
    default_name = f"Legacy {schema_name}"
    default_code = schema_name[:64]

    customer, _ = Customer.objects.get_or_create(
        name=default_name,
        defaults={
            "code": default_code,
            "is_enabled": True,
            "metadata": {"migrated_from_schema": schema_name},
        },
    )

    if not customer.code:
        customer.code = default_code
        customer.save(update_fields=["code", "updated_at"])

    Alert.objects.filter(customer__isnull=True).update(customer_id=customer.id)
    Source.objects.filter(customer__isnull=True).update(customer_id=customer.id)
    SavedSearch.objects.filter(customer__isnull=True).update(customer_id=customer.id)
    NotificationEvent.objects.filter(customer__isnull=True).update(customer_id=customer.id)
    IngestionRun.objects.filter(customer__isnull=True).update(customer_id=customer.id)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_data', '0006_attachment_scan_and_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_enabled', 'name'], name='cust_enabled_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('name',), name='tenant_data_customer_name_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alert',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='tenant_data.customer'),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to='tenant_data.customer'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tenant_data.customer'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to='tenant_data.customer'),
        ),
        migrations.AddField(
            model_name='source',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='tenant_data.customer'),
        ),
        migrations.RunPython(backfill_customer_relations, noop_reverse),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['customer', '-event_timestamp'], name='alert_customer_event_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['customer', 'severity'], name='alert_customer_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['customer', 'source_name'], name='alert_customer_source_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['customer', '-started_at'], name='ingrun_customer_started_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['customer', 'is_active', '-created_at'], name='notif_cust_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['customer', 'user'], name='savedsearch_customer_user_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['customer', 'type', 'is_enabled'], name='src_cust_type_enabled_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together={('user', 'customer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('customer', 'name', 'type')},
        ),
    ]
