# Generated by Django 4.2.19 on 2026-03-03 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_data', '0007_customer_alert_alert_customer_event_ts_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDetailFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=150)),
                ('alert_type', models.CharField(max_length=255)),
                ('visible_fields', models.JSONField(blank=True, default=list)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_detail_field_configs', to='tenant_data.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_detail_field_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('source_name', 'alert_type', 'id'),
                'indexes': [models.Index(fields=['customer', 'user', 'source_name', 'alert_type'], name='alertdetailcfg_scope_idx')],
                'unique_together': {('user', 'customer', 'source_name', 'alert_type')},
            },
        ),
    ]
