# Generated by Django 4.2.19 on 2026-03-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_data', '0008_alertdetailfieldconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('imap', 'IMAP'), ('rest', 'REST'), ('webhook', 'Webhook'), ('syslog_udp', 'Syslog UDP'), ('syslog_tcp', 'Syslog TCP'), ('kafka_topic', 'Kafka Topic'), ('s3_bucket', 'S3 Bucket'), ('azure_event_hub', 'Azure Event Hub'), ('gcp_pubsub', 'GCP Pub/Sub'), ('sftp_drop', 'SFTP Drop')], max_length=20),
        ),
        migrations.CreateModel(
            name='SourceAlertTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_name', models.CharField(max_length=255)),
                ('match_mode', models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('regex', 'Regex')], default='exact', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_type_rules', to='tenant_data.source')),
            ],
            options={
                'ordering': ('alert_name', 'id'),
                'indexes': [models.Index(fields=['source', 'is_enabled'], name='srcalrule_src_enabled_idx'), models.Index(fields=['source', 'alert_name'], name='srcalrule_src_name_idx')],
                'unique_together': {('source', 'alert_name', 'match_mode')},
            },
        ),
    ]
