# Generated by Django 4.2.19 on 2026-03-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_data', '0009_source_description_alter_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Gold', max_length=20)),
                ('timezone', models.CharField(default='Europe/Rome', max_length=64)),
                ('sla_target', models.CharField(default='15m', max_length=64)),
                ('primary_contact', models.CharField(default='SOC Lead', max_length=150)),
                ('contact_email', models.EmailField(default='soc@example.com', max_length=254)),
                ('contact_phone', models.CharField(default='+39 000 000 000', max_length=64)),
                ('notify_channels', models.CharField(default='Email, Slack, PagerDuty', max_length=255)),
                ('escalation_matrix', models.CharField(default='L1 -> L2 -> L3', max_length=255)),
                ('maintenance_window', models.CharField(default='Sunday 02:00 - 03:00', max_length=255)),
                ('default_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('auto_assign_team', models.CharField(default='SOC L1', max_length=120)),
                ('notify_on_critical', models.BooleanField(default=True)),
                ('notify_on_high', models.BooleanField(default=True)),
                ('allow_suppress', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('tag_defaults', models.CharField(default='customer, socview', max_length=255)),
                ('enrich_geo', models.BooleanField(default=True)),
                ('enrich_threat_intel', models.BooleanField(default=True)),
                ('allow_external_sharing', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenant_data.customer')),
            ],
            options={
                'ordering': ('customer_id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSourcePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_preferences', to='tenant_data.customer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_preferences', to='tenant_data.source')),
            ],
            options={
                'ordering': ('customer_id', 'source_id'),
                'indexes': [models.Index(fields=['customer', 'is_enabled'], name='custsrcpref_cust_enabled_idx'), models.Index(fields=['source', 'is_enabled'], name='custsrcpref_src_enabled_idx')],
                'unique_together': {('customer', 'source')},
            },
        ),
    ]
