# Generated by Django 4.2.19 on 2026-03-03 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _backfill_memberships(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    Customer = apps.get_model("tenant_data", "Customer")
    CustomerMembership = apps.get_model("tenant_data", "CustomerMembership")

    customer_ids = list(Customer.objects.values_list("id", flat=True))
    if not customer_ids:
        return

    existing_pairs = set(CustomerMembership.objects.values_list("user_id", "customer_id"))
    default_scope = {
        "SUPER_ADMIN": "manager",
        "SOC_MANAGER": "manager",
        "SOC_ANALYST": "triage",
        "READ_ONLY": "viewer",
    }

    to_create = []
    for user_id, role in User.objects.filter(is_active=True).values_list("id", "role"):
        scope = default_scope.get(role, "viewer")
        for customer_id in customer_ids:
            pair = (user_id, customer_id)
            if pair in existing_pairs:
                continue
            to_create.append(
                CustomerMembership(
                    user_id=user_id,
                    customer_id=customer_id,
                    scope=scope,
                    is_active=True,
                    notes="Backfill automatico migrazione RBAC",
                )
            )
            existing_pairs.add(pair)

    if to_create:
        CustomerMembership.objects.bulk_create(to_create, batch_size=500)


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_data', '0010_customersettings_customersourcepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('viewer', 'Viewer'), ('triage', 'Triage'), ('manager', 'Manager')], default='triage', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenant_data.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('customer_id', 'user_id'),
                'indexes': [models.Index(fields=['user', 'is_active'], name='custmemb_user_active_idx'), models.Index(fields=['customer', 'is_active'], name='custmemb_customer_active_idx'), models.Index(fields=['scope', 'is_active'], name='custmemb_scope_active_idx')],
                'unique_together': {('user', 'customer')},
            },
        ),
        migrations.RunPython(_backfill_memberships, _noop_reverse),
    ]
