# Generated by Django 4.2.19 on 2026-03-04 17:44

import django.contrib.postgres.indexes
from django.db import migrations, models
import tenant_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_data', '0011_customermembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('response_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('severity', 'id'),
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='iocs',
            field=models.JSONField(blank=True, default=tenant_data.models.default_alert_iocs),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_technique_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['iocs'], name='alert_iocs_gin_idx'),
        ),
        migrations.AddConstraint(
            model_name='slaconfig',
            constraint=models.UniqueConstraint(fields=('severity',), name='sla_config_severity_unique'),
        ),
    ]
