export type SourceAdvancedConfig = {
  headerName: string;
  apiKeyName: string;
  oauthTokenUrl: string;
  usernameRef: string;
  passwordRef: string;
  verifyTls: boolean;
  signatureHeader: string;
  webhookSecret: string;
  pollingIntervalSeconds: number;
  rateLimitPerMinute: number;
  timeoutSeconds: number;
  retryCount: number;
  backoffSeconds: number;
  healthStatus: "healthy" | "warning" | "error";
  lastCheckAt: string;
  lastError: string;
  dedupStrategy: string;
  dedupWindowMinutes: number;
  dedupFields: string;
  parseMode: string;
  dropUnknown: boolean;
  timezone: string;
  mappingVersion: string;
  retentionDays: number;
  defaultSeverity: string;
  defaultTags: string;
};
